### ISSUE TITLE
Cannot set SMTPPort ('number' must be 'string')

### ISSUE THREAD

**Issue by fnerdwq** [liger1978/mattermost#15]
Hi, 
it is not possible with your current setup in `config.json.erb` set the `override_options => EmailSettings => SMTPPort`.

When setting this value to `25` it's handled as an number and therefore saved w/o quotes in json. But mattermost expects string here.
Adding the quotes explicitly doesn't work as well, since then they are added twice.

**Comment by liger1978** [comment]
Fixed.  Specify `SMTPPort` as a string.  New version released to forge.
