### ISSUE TITLE
Can't configure SMTPPort because of Data Type

### ISSUE THREAD

**Issue by FencyToni** [liger1978/mattermost#5]
Hello liger1978

I wanted to try your module and I had problems by configuring the SMTPPort in my manifest with the override_option. It seems that augeas wants to have a String there but the Data Type is Number if i want to configure port 25. Can you help me?

Output from error by puppet:
_Debug: Augeas[/opt/mattermost-2.0.0/config/config.json](provider=augeas): sending command 'set' with params ["/files/opt/mattermost-2.0.0/config/config.json/dict/entry[ . = 'EmailSettings']/dict/entry[ . = 'SMTPPort']", "SMTPPort"]
Debug: Augeas[/opt/mattermost-2.0.0/config/config.json](provider=augeas): sending command 'set' with params ["/files/opt/mattermost-2.0.0/config/config.json/dict/entry[ . = 'EmailSettings']/dict/entry[ . = 'SMTPPort']/number", "25"]
Debug: Augeas[/opt/mattermost-2.0.0/config/config.json](provider=augeas): /augeas/files/opt/mattermost-2.0.0/config/config.json/error/lens = /opt/puppetlabs/puppet/share/augeas/lenses/dist/json.aug:41.15-.56:
Debug: Augeas[/opt/mattermost-2.0.0/config/config.json](provider=augeas): /augeas/files/opt/mattermost-2.0.0/config/config.json/error/message = Failed to match 

<<rec>>
  with tree
    { "string" } { "number" = "25" }
Debug: Augeas[/opt/mattermost-2.0.0/config/config.json](provider=augeas): Closed the augeas connection
Error: /Stage[main]/Mattermost::Config/Augeas[/opt/mattermost-2.0.0/config/config.json]: Could not evaluate: Saving failed, see debug_

**Comment by liger1978** [comment]
Will look into this ASAP.

**Comment by liger1978** [comment]
@FencyToni Can I see the extract from your manifest please?

**Comment by liger1978** [comment]
This works fine for me:

``` puppet
class { 'mattermost':
  override_options => {
    'EmailSettings'     => {
      'SMTPPort' => 25,
    }
  },
}
```
