### ISSUE TITLE
'conf' is declared more than once in init.pp

### ISSUE THREAD

**Issue by chihoko** [liger1978/mattermost#7]
Thanks for this module. Running it on puppetserver 2.3.1 throws the following error which can be verified in init.pp.

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: The parameter 'conf' is declared more than once in the parameter list at /etc/puppetlabs/code/environments/production/modules/mattermost/manifests/init.pp:16:3`

**Comment by liger1978** [comment]
Patched by @gguillotte . Will release to Forge later. Thanks.
